
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class Principal3 extends javax.swing.JFrame {

    /**
     * Creates new form Principal3
     */
    double v[];
    public Principal3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeros = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtCrear = new javax.swing.JButton();
        txtLlenarManual = new javax.swing.JButton();
        txtLlenarAuto = new javax.swing.JButton();
        txtMostrar = new javax.swing.JButton();
        txtBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCantidadesPares = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCantidadImpares = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCantidadesPrimos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("De los n elementos de un vector #2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 260, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inicial"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Numeros");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 50));

        txtNumeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerosKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCrear.setText("Crear");
        txtCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrearActionPerformed(evt);
            }
        });
        jPanel2.add(txtCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, 100, -1));

        txtLlenarManual.setText("Llenar Manual");
        txtLlenarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLlenarManualActionPerformed(evt);
            }
        });
        jPanel2.add(txtLlenarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 49, -1, -1));

        txtLlenarAuto.setText("Llenar Auto");
        txtLlenarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLlenarAutoActionPerformed(evt);
            }
        });
        jPanel2.add(txtLlenarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 78, 100, -1));

        txtMostrar.setText("Mostrar");
        txtMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(txtMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 107, 100, -1));

        txtBorrar.setText("Borrar");
        txtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(txtBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 136, 100, -1));

        jLabel3.setText("Opciones");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 140, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Pares"));

        txtCantidadesPares.setEditable(false);
        txtCantidadesPares.setColumns(20);
        txtCantidadesPares.setRows(5);
        jScrollPane1.setViewportView(txtCantidadesPares);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Impares"));

        txtCantidadImpares.setEditable(false);
        txtCantidadImpares.setColumns(20);
        txtCantidadImpares.setRows(5);
        jScrollPane2.setViewportView(txtCantidadImpares);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Primos"));

        txtCantidadesPrimos.setEditable(false);
        txtCantidadesPrimos.setColumns(20);
        txtCantidadesPrimos.setRows(5);
        jScrollPane3.setViewportView(txtCantidadesPrimos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearActionPerformed
        // TODO add your handling code here:
        int numeros;
        if (txtNumeros.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Digite el numero","ERROR",JOptionPane.ERROR_MESSAGE);
        
        txtNumeros.requestFocusInWindow();
        } else if (Integer.parseInt(txtNumeros.getText().trim())==0){
        JOptionPane.showMessageDialog(this, "El numero no puede ser cero","ERROR",JOptionPane.ERROR_MESSAGE);
        txtNumeros.requestFocusInWindow();
        txtNumeros.selectAll();
        
        }else{
        numeros= Integer.parseInt(txtNumeros.getText().trim());
        v= new double [numeros];
        JOptionPane.showMessageDialog (this, "El vector se ha creado exitosamente");
        
        
        }
    }//GEN-LAST:event_txtCrearActionPerformed

    private void txtNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerosKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
          if (!Character.isDigit(c)){
          
          getToolkit().beep();
          evt.consume();
          }
          
    }//GEN-LAST:event_txtNumerosKeyTyped

    private void txtLlenarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLlenarManualActionPerformed
        // TODO add your handling code here:
        double s;
        for (int i=0; i<v.length; i++) {
        s= Double.parseDouble(JOptionPane.showInputDialog(this, "Digite el elemento en la posicion"+i));
        v[i]=s;
        
        }
    }//GEN-LAST:event_txtLlenarManualActionPerformed

    private void txtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostrarActionPerformed
        // TODO add your handling code here:
        
        int pares = 0, impares = 0; 
        for (int i=0; i<v.length; i++) {
            
            if(v[i]%2==0){
             pares++;
             txtCantidadesPares.append(v[i]+ " ");
             }
            
              else{
               impares++;
               txtCantidadImpares.append(v[i]+ " ");
            }
        
        
        int conta=0, primos = 0;
            for(int b=1; b<= v[i]; b++){
              if(v[i]%b==0){
              conta++;
          }
       }
            
            if(conta==2){
              primos++;
              txtCantidadesPrimos.append(v[i]+ " ");
            }
            }
        
    }//GEN-LAST:event_txtMostrarActionPerformed

    private void txtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrarActionPerformed
        // TODO add your handling code here:
        
        txtNumeros.setText("");
        txtCantidadesPares.setText("");
        txtCantidadImpares.setText("");
        txtCantidadesPrimos.setText("");
        
        v = null;
        txtNumeros.requestFocusInWindow();
        
        v = null;
        txtNumeros.requestFocusInWindow();
    }//GEN-LAST:event_txtBorrarActionPerformed

    private void txtLlenarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLlenarAutoActionPerformed
        // TODO add your handling code here:
        int s;
        for (int i=0; i<v.length; i++) {
        s= (int) (Math.random()*50+1);
        
        v[i]=s;
        
        JOptionPane.showMessageDialog(this, "Vector Llenado Correctamente");
        }
    }//GEN-LAST:event_txtLlenarAutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton txtBorrar;
    private javax.swing.JTextArea txtCantidadImpares;
    private javax.swing.JTextArea txtCantidadesPares;
    private javax.swing.JTextArea txtCantidadesPrimos;
    private javax.swing.JButton txtCrear;
    private javax.swing.JButton txtLlenarAuto;
    private javax.swing.JButton txtLlenarManual;
    private javax.swing.JButton txtMostrar;
    private javax.swing.JTextField txtNumeros;
    // End of variables declaration//GEN-END:variables
}
